### PR TITLE
NTP-720: Shortlisting TPs MVP

### PR DESCRIPTION
**Pull request by ashward**
## Link to Jira ticket

https://dfedigital.atlassian.net/browse/NTP-720

## Things to check

- [x] Title is in the format "NTP-XXX: Short description" where NTP-XXX is the Jira ticket reference
- [ ] Code and tests follow the [coding standards](/docs/coding-standards.md)
- [ ] `dotnet format` has been run in the repository root
- [ ] Test coverage of new code is at least 80%
- [ ] All UI related acceptance criteria specified in the ticket have been added to the relevant [cypress test feature file(s)](/UI/cypress/e2e/)
- [ ] Unless explicitly mentioned in the ticket, all UI work should have been tested as working on desktop and mobile resolutions with JavaScript on and off
- [ ] Database migrations can be applied to the current codebase in main without causing exceptions
- [ ] Debug logging has been added after all logic decision points
- [ ] All [automated testing](/README.md#testing) including accessibility and security has been run against your code
- [ ] **PR deployment has been signed off by wider team**

### CODE REVIEW

**Comment by ashward** [comment]
I noticed that the shortlist checkbox isn't displayed as a GOV.UK style checkbox, but is just a normal native one. Could we make it a GOV.UK style one please?
image

**Comment by ashward** [comment]
Also we could add `vertical-align: middle` to the `<dt>` on that row so that the text vertically aligns better?
image

**Comment by Kolapo-Abolarinwa** [comment]
> I noticed that the shortlist checkbox isn't displayed as a GOV.UK style checkbox, but is just a normal native one. Could we make it a GOV.UK style one please?
> image

Sure, I will look into it again. I tried using the gov checkbox initially but I was having issues with the way it works with its label and its styling. So I tried to re-create the look and feel but it appears I missed some things👍

**Review by kieranohanlon — APPROVED** [review]
Looks good

**Review by Kolapo-Abolarinwa — APPROVED** [review]

**Pull request merged**
